### PR TITLE
bin/ in ~syseleven was owned by root:root

### PR DESCRIPTION
**Pull request by funkestefan**

### CODE REVIEW

**Comment by stefreak** [comment]
@LarsFronius says root cause for this issue could be the "syselven" user. maybe we stick with the defaults to keep things simple?

**Comment by LarsFronius** [comment]
imho we are creating a lot of complexity by making sure the username is syseleven, whereas I bet most of the tooling will just try to use the ubuntu user as it is de-facto the standard on a ubuntu machine.
I don't see a good reason to change to a syseleven user via user-data - if this was our very own image, sure, but not if we de facto boot up a unchanged ubuntu image.

**Comment by stefreak** [comment]
I tend to agree ... complexity should only be there for a really good reason. Also, when I started out with SysEleven Stack I expected "ubuntu" as a default user for an ubuntu system

**Comment by jpeschkeSys11** [comment]
the directory ~/bin is created by root during the cloudinit run. It has nothing to do with the user syseleven.

**Pull request merged**
